spring:
  application:
    name: finanzas-backend

  datasource:
    url: jdbc:postgresql://aws-0-ca-central-1.pooler.supabase.com:5432/postgres?sslmode=require

    username: postgres.bwyddteiwyhpvmpbvdgs

    password: ${DB_PASSWORD}

    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080


supabase:
  jwt:
    secret: ${JWT_SECRET}